apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-go2rtc
  namespace: frigate
data:
  go2rtc.yaml: |-
    log:
      level: debug  # default level
      api: trace
      exec: debug
      ngrok: info
      rtsp: warn
      streams: error
      webrtc: fatal
    streams:
      Exterior_Driveway_Camera:
        - onvif://frigate:frigate1577@172.20.248.43
        - ffmpeg:Exterior_Driveway_Camera#hardware#video=h264#width=1920#audio=copy
        - ffmpeg:Exterior_Driveway_Camera#hardware#video=h264#width=1024#audio=copy
      Exterior_Walkway_Gate_Camera:
        - onvif://frigate:frigate1577@172.20.248.186
        - ffmpeg:Exterior_Walkway_Gate_Camera#hardware#video=h264#width=1920#audio=copy
        - ffmpeg:Exterior_Walkway_Gate_Camera#hardware#video=h264#width=1024#audio=copy
      Garage_Camera_1:
        - ffmpeg:rtsp://frigate:frigate1577@172.20.249.124:554/cam/realmonitor?channel=1&subtype=0#hardware#video&audio=copy
        - ffmpeg:Garage_Camera_1#hardware#video=h264#width=1920#audio=copy
        - ffmpeg:Garage_Camera_1#hardware#video=h264#width=1024#audio=copy
      Mudroom_Hallway_Camera:
        - ffmpeg:rtsp://172.20.248.243:554/stream1#input=rtsp/udp#hardware#video&audio=copy
        - ffmpeg:Mudroom_Hallway_Camera#hardware#video=h264#width=1920#audio=copy
        - ffmpeg:Mudroom_Hallway_Camera#hardware#video=h264#width=1024#audio=copy
      Basement_Office_Camera:
        - onvif://frigate:frigate1577@172.20.248.130
        - ffmpeg:Basement_Office_Camera#hardware#video=h264#width=1920#audio=copy
        - ffmpeg:Basement_Office_Camera#hardware#video=h264#width=1024#audio=copy
      Basement_Mechanical_Camera_1:
        - onvif://frigate:frigate1577@172.20.248.36
        - ffmpeg:Basement_Mechanical_Camera_1#hardware#video=h264#width=1920#audio=copy
        - ffmpeg:Basement_Mechanical_Camera_1#hardware#video=h264#width=1024#audio=copy
      Basement_Mechanical_Camera_2:
        - onvif://frigate:frigate1577@172.20.248.25
        - ffmpeg:Basement_Mechanical_Camera_2#hardware#video=h264#width=1920#audio=copy
        - ffmpeg:Basement_Mechanical_Camera_2#hardware#video=h264#width=1024#audio=copy
      Basement_3D_Printer_Pinky:
        - ffmpeg:rtsp://pinky.farhoodliquor.lan:8554/stream.h264#hardware#video&audio=copy
      Basement_3D_Printer_TheBrain:
        - ffmpeg:rtsp://thebrain.farhoodliquor.lan:8554/stream.h264#hardware#video&audio=copy
    candidates:
      - 108.254.166.31:8555
      - stun:8555