## ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-go2rtc
  namespace: frigate
data:
  go2rtc.yaml: |-
    log:
      level: debug  # default level
      api: trace
      exec: debug
      ngrok: info
      rtsp: warn
      streams: error
      webrtc: fatal
    streams:
      Basement_Mechanical_1-Unifi-G3-Pro: ffmpeg:rtsps://192.168.192.250:7441/SA0SZPTx8Bm1ghRi?enableSrtp#hardware#video=h264
      Basement_Mechanical_2-Unifi-G3-Pro: ffmpeg:rtsps://192.168.192.250:7441/CHiX5iz19kAAvE9P?enableSrtp#video=h264
      Basement_3D_Printer_Pinky: ffmpeg:rtsp://pinky.farhoodliquor.lan:8554/stream.h264#hardware#video=h264
      Basement_3D_Printer_The_Brain: ffmpeg:rtsp://thebrain.farhoodliquor.lan:8554/stream.h264#hardware#video=h264
    webrtc:
      candidates:
      - frigate-0:8555
      - stun:8555        
