## ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-go2rtc
  namespace: frigate
data:
  go2rtc.yaml: |-
    log:
      level: debug  # default level
      api: trace
      exec: debug
      ngrok: info
      rtsp: warn
      streams: error
      webrtc: fatal
    streams:
      Basement_3D_Printer_Pinky: ffmpeg:rtsp://pinky.farhoodliquor.lan:8554/stream.h264#hardware#video=copy
      Basement_3D_Printer_The_Brain: ffmpeg:rtsp://thebrain.farhoodliquor.lan:8554/stream.h264#hardware#video=copy
      Basement_Office_1-Armcrest-ProHD-Raw: rtsp://go2rtc:frigate1577@192.168.192.55:554/live
      Basement_Office_1-Armcrest-ProHD: ffmpeg:rtsp://go2rtc.nvr.k8s:8554/Basement_Office_1-Armcrest-ProHD-Raw#hardware#video=h264#width=1920
      Basement_Office_1-Armcrest-ProHD-Detect: ffmpeg:rtsp://go2rtc.nvr.k8s:8554/Basement_Office_1-Armcrest-ProHD-Raw#hardware#video=h264#width=1024
    webrtc:
      candidates:
      - frigate-0:8555
      - stun:8555        
