## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
spec:
  selector:
    matchLabels:
      app: go2rtc
  replicas: 2
  template:
    metadata:
      labels:
        app: go2rtc
    spec:
      containers:
        - name: go2rtc # https://github.com/AlexxIT/go2rtc
          image: alexxit/go2rtc:latest-hardware
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Detroit"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
              gpu.intel.com/i915: 1
          ports:
            - name: "web"
              containerPort: 1984
            - name: "rtsp"
              containerPort: 8554
            - name: "webrtc"
              containerPort: 8555
            - name: "webrtc-udp"
              containerPort: 8555
              protocol: UDP
          volumeMounts:
            - name: go2rtc-config
              mountPath: /config
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 5
      volumes:
        - name: go2rtc-config
          configMap:
            name: configmap-go2rtc
