apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: nvr
spec:
  chart:
    spec:
      chart: frigate
      version: 7.6.x
      sourceRef:
        kind: HelmRepository
        name: blakeshome-charts
        namespace: nvr
  interval: 15m
  timeout: 14m
  releaseName: frigate
  values:
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
        gpu.intel.com/i915: 1
    securityContext:
      privileged: true
    podAnnotations: {}
    shmSize: 128Mi
    tmpfs:
      enabled: true
      sizeLimit: 256Mi
    config: |
      tls:
        enabled: false
      mqtt:
        enabled: true
        host: homeassistant.farhoodliquor.lan
        user: frigate
        password: frigate1577
      ffmpeg:
        hwaccel_args: preset-vaapi
      detectors:
        cpai:
          api_url: http://aiserver:32168/v1/vision/detection
          type: deepstack
          api_timeout: 0.5
      detect:
        enabled: true
        min_initialized: 2
      objects:
        track:
          - person
      motion:
        enabled: true
      snapshots:
        enabled: true
        clean_copy: true
        timestamp: true
        retain:
          default: 2
          objects:
            person: 7
      record:
        enabled: true
        retain:
          days: 1
          mode: all
        events:
          retain:
            default: 30
            mode: active_objects
      cameras:
        Basement_3D_Printer_Pinky:
          webui_url: https://pinky.farhoodliquor.com
          ui:
            order: 501
            dashboard: true
          detect:
            enabled: false
          audio:
            enabled: false
          ffmpeg:
            inputs:
              - path: rtsp://localhost:8554/Basement_3D_Printer_Pinky
                roles:
                  - detect
                  - record
          live:
            stream_name: Basement_3D_Printer_Pinky
          zones: {}
        Basement_3D_Printer_TheBrain:
          webui_url: https://thebrain.farhoodliquor.com
          ui:
            order: 502
            dashboard: true
          detect:
            enabled: false
          audio:
            enabled: false
          ffmpeg:
            inputs:
              - path: rtsp://localhost:8554/Basement_3D_Printer_TheBrain
                roles:
                  - record
                  - detect
          live:
            stream_name: Basement_3D_Printer_TheBrain
          zones: {}
      go2rtc:
        streams:
          Basement_3D_Printer_Pinky:
            - ffmpeg:rtsp://pinky.farhoodliquor.lan:8554/stream.h264#hardware#video&audio=copy
          Basement_3D_Printer_TheBrain:
            - ffmpeg:rtsp://thebrain.farhoodliquor.lan:8554/stream.h264#hardware#video&audio=copy
        webrtc:
          candidates:
            - frigate.nvr.animaniacs.farh.net:8555
            - stun:8555
    service:
      type: LoadBalancer
    persistence:
      config:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 1Gi
        skipuninstall: false
      media:
        enabled: true
        existingClaim: frigate-media
        storageClass: "ceph-filesystem"
        accessMode: ReadWriteMany
        size: 256Gi
        skipuninstall: false