apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate-exterior
  namespace: nvr
spec:
  chart:
    spec:
      chart: frigate
      version: 7.6.x
      sourceRef:
        kind: HelmRepository
        name: blakeshome-charts
        namespace: nvr
  interval: 1h
  timeout: 15m
  releaseName: frigate-exterior
  values:
    resources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"
        gpu.intel.com/i915: 1
    securityContext:
      privileged: true
    podAnnotations: {}
    shmSize: 512Mi
    tmpfs:
      enabled: true
      sizeLimit: 1024Mi
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        service.cilium.io/forwarding-mode: dsr
    ingress:
      enabled: true
      ingressClassName: traefik-internal
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: frigate-exterior.animaniacs.farh.net
          paths:
            - path: '/'
              portName: http-auth
      tls:
        - secretName: frigate-exterior.animaniacs.farh.net-cert
          hosts:
            - frigate-exterior.animaniacs.farh.net
    persistence:
      config:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 4Gi
        skipuninstall: true
    extraVolumes:
    - name: nfs-media
      nfs:
        server: spielberg.dmz.farh.net
        path: /mnt/pool1/frigate/exterior
    extraVolumeMounts:
    - name: nfs-media
      mountPath: "/media/frigate"