## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiserver-coral
spec:
  ingressClassName: traefik-internal
  rules:
  - host: aiserver.animaniacs.farh.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  aiserver
            port:
              number: 32168