# This is for the main flux-system git repository
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: cpfarhood-nvr
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token-nvr
  resources:
    - kind: GitRepository
      name: cpfarhood-nvr
      namespace: nvr