apiVersion: v1
kind: Service
metadata:
  name: frigate-detect
  labels:
    app.kubernetes.io/name: frigate-detect
spec:
  selector:
    app.kubernetes.io/name: frigate-detect
  type: LoadBalancer
  externalTrafficPolicy: Local  # This must be "Cluster" for ip sharing
  ports:
  - port: 8971
    targetPort: 8971
    name: http-8971
  - port: 5000
    targetPort: 5000
    name: http-5000
  - port: 8554
    targetPort: 8554
    name: rtsp
  - port: 8555
    targetPort: 8555
    name: webrtc
  - port: 8555
    protocol: UDP
    targetPort: 8555
    name: webrtc-udp