## Service
---
apiVersion: v1
kind: Service
metadata:
  name: scrypted
  labels:
    app.kubernetes.io/name: scrypted
spec:
  selector:
    app.kubernetes.io/name: scrypted
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 11080
    targetPort: 11080
    name: http
  - port: 10443
    targetPort: 10443
    name: https
