## Service
---
apiVersion: v1
kind: Service
metadata:
  name: aiserver
  labels:
    app.kubernetes.io/name: aiserver
spec:
  selector:
    app.kubernetes.io/name: aiserver
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 5000
    name: http
  - port: 32168
    targetPort: 32168
    name: http-32168

