## Service
---
apiVersion: v1
kind: Service
metadata:
  name: firstfloor
  labels:
    app.kubernetes.io/name: firstfloor
#  annotations:
#    metallb.universe.tf/allow-shared-ip: "frigate"
spec:
  selector:
    app.kubernetes.io/name: firstfloor
  type: LoadBalancer
  externalTrafficPolicy: Local # This must be "Cluster" for ip sharing
  ports:
  - port: 1984
    targetPort: 1984
    name: http-1984
  - port: 8554
    targetPort: 8554
    name: rtsp
  - port: 8555
    targetPort: 8555
    name: webrtc
  - port: 8555
    protocol: UDP
    targetPort: 8555
    name: webrtc-udp