## Service
---
apiVersion: v1
kind: Service
metadata:
  name: aiserver
  labels:
    app.kubernetes.io/name: aiserver
spec:
  selector:
    app.kubernetes.io/name: aiserver
  type: LoadBalancer
  # Keep internal traffic local to the node as we're running a daemonset
  internalTrafficPolicy: Local
  # Distribute traffic across all nodes for external requests
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 5000
    name: http
  - port: 32168
    targetPort: 32168
    name: http-32168

