## Service
---
apiVersion: v1
kind: Service
metadata:
  name: 3dprinters
  labels:
    app.kubernetes.io/name: 3dprinters
spec:
  selector:
    app.kubernetes.io/name: 3dprinters
  type: LoadBalancer
  externalTrafficPolicy: Local # This must be "Cluster" for ip sharing
  ports:
  - port: 1984
    targetPort: 1984
    name: http-1984
  - port: 8554
    targetPort: 8554
    name: rtsp
  - port: 8555
    targetPort: 8555
    name: webrtc
  - port: 8555
    protocol: UDP
    targetPort: 8555
    name: webrtc-udp