## Service
---
apiVersion: v1
kind: Service
metadata:
  name: deepstack
  labels:
    app.kubernetes.io/name: deepstack
spec:
  selector:
    app.kubernetes.io/name: deepstack
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 5000
    name: http

