## Service
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  labels:
    app: frigate
  annotations:
    metallb.universe.tf/allow-shared-ip: "frigate"
    metallb.universe.tf/loadBalancerIPs: 65.43.40.110
spec:
  selector:
    app: frigate
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 8971
    targetPort: 8971
    name: http-8971
  - port: 5000
    targetPort: 5000
    name: http-5000
#  - port: 8554
#    targetPort: 8554
#    name: rtsp
#  - port: 8555
#    targetPort: 8555
#    name: webrtc
#  - port: 8555
#    protocol: UDP
#    targetPort: 8555
#    name: webrtc-udp
    
