apiVersion: v1
kind: Service
metadata:
  name: aiserver
  labels:
    app.kubernetes.io/name: aiserver
  annotations:
    service.cilium.io/forwarding-mode: dsr
spec:
  selector:
    app.kubernetes.io/name: aiserver
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 5000
    name: http
  - port: 32168
    targetPort: 32168
    name: http-32168

