## Service
---
apiVersion: v1
kind: Service
metadata:
  name: go2rtc
  labels:
    app.kubernetes.io/name: go2rtc
spec:
  selector:
    app.kubernetes.io/name: go2rtc
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 1984
    name: http
  - port: 8554
    targetPort: 8554
    name: rtsp
  - port: 8555
    targetPort: 8555
    name: webrtc
  - port: 8555
    protocol: UDP
    targetPort: 8555
    name: webrtc-udp
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go2rtc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go2rtc
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60