## StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aiserver
  labels:
    app.kubernetes.io/name: aiserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aiserver
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
           matchExpressions:
            - key: <label-key>
              operator: In
              values:
              - <label-value>
          topologyKey: kubernetes.io/hostname
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aiserver
    spec:
      containers:
        - name: ai-server 
          image: codeproject/ai-server:2.8.0
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "America/Detroit"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "6Gi"
              cpu: "4000m"
              squat.ai/coral: 1
          ports:
          - name: "http-32168"
            containerPort: 32168
          volumeMounts:
          - name: config
            mountPath: "/etc/codeproject/ai"
          - name: modules
            mountPath: "/app/modules"
          readinessProbe:
            httpGet:
              path: /
              port: http-32168
          livenessProbe:
            httpGet:
              path: /
              port: http-32168
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn-perpetual
      resources:
        requests:
          storage: 4Gi
  - metadata:
      name: modules
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn-perpetual
      resources:
        requests:
          storage: 8Gi
---

## Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aiserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: aiserver
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
---