
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frigate-interior-media
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate-interior
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "256Gi"
  storageClassName: "ceph-filesystem"
