---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-exterior-media-pv
  labels:
    app: frigate-exterior
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/pool0/frigate/exterior
    server: spielberg.dmz.farh.net
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-exterior-media
  labels:
    app: frigate-exterior
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: frigate-exterior