apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: cpfarhood-nvr
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: cpfarhood-nvr
      namespace: nvr